### ISSUE TITLE
给几个建议

### ISSUE THREAD

**Issue by chise0713** [H3d9/memory_cleaner#1]
可以多加几个自定义选项吗？
例如
自定义内存占用多少%进行某项清理；
自定义多少分钟之后进行某项清理；
自定义是否存在于任务栏中；
//
并且希望可以加上几个可以让cmd调用的命令，这样就也可以不使用gui界面运行这个应用了

**Comment by H3d9** [comment]
1. 默认情况Windows的内存管理机制在物理内存达到80%开始页面交换，所以自定义没有太大的必要，若你需要自行修改一下源码编译即可；反而小白会胡乱设置导致出各种卡顿问题。
2. 同上。
3. 直接关掉就会在托盘后台运行；如果托盘都没图标就只能任务管理器结束了，这样并不好。
4. cmd命令执行时，加入“silent”开关，即可不启用gui界面而直接后台运行。
