### ISSUE TITLE
不知道能否提供arm64版本？

### ISSUE THREAD

**Issue by Grosser-Kurfuerst** [H3d9/memory_cleaner#2]
目前正在使用win on arm设备，虽然x64可以转译运行，但要是能提供原生arm版本就更好了，十分感谢!

**Comment by H3d9** [comment]
直接仿真运行即可，同为windows平台清理内存使用的系统调用是一样的。
即使出于性能考虑，由于都是NT内核，异构仿真仅需转译指令，其代价可以完全忽略不计，因为系统调用完全一致。
