### ISSUE TITLE
【功能请求】能否保存开机时的默认进程，以便随时恢复？

### ISSUE THREAD

**Issue by jkqxl** [H3d9/memory_cleaner#4]
应用场景：经过测试，一些游戏，在windows10重启后，相对来说运行更加流畅，而在已经使用很多程序，即便是关闭它们后再使用 memory_cleaner 软件 执行清理，依然无效，即同样的游戏，系统重启则不会卡顿。因此，提出一个想法，如果可以将系统默认开机进程备份，使用时清理掉多余的，那么能否就可以解决掉这个问题呢？

功能建议：增加一个备份进程服务的功能，以及一个恢复的功能按钮。

其它：当然不确定的是，这个操作是否有效，还是需要测试。

参考：https://blog.csdn.net/NaShiWoMenHuanXiao/article/details/104845598
这个WIN系统自带命令比重启还要厉害，重启电脑后会有三个应用程序开机启动，而使用这个指令则只有一个应用程序自己启动，而且这个应用程序还是杀毒软件。本人测试，除了一些杀毒软件，如火绒，还有系统催化剂不会清理掉外，其它都会被清理掉，包括需要的鼠标驱动、memory_cleaner等，因此两者如果能够综合下就太好了。以此延伸出的另一种思路是，先清理掉所有，再启动已经保存好的想要启动的程序服务（自动对比系统默认重启后的服务，或者自己设置）

**Comment by H3d9** [comment]
系统里运行的东西除了你在任务管理器看见的那些进程，还有内核中运行的东西，就算你只保留某些程序而把其他你看见的进程全部kill掉，依然无法做到流畅，而且手动卸载驱动模块是非常危险且毫无必要的操作。

正常情况下如果你关闭一个程序，系统会自动回收他的内存，所以应该没有关了软件还清理不掉内存或清理后仍然卡顿的问题，除非以下极端情况：

> 进程退出时未卸载或延迟卸载驱动模块，而驱动中仍有内核线程在运行，导致cpu、磁盘占用（点名表扬tp驱动）
> 某个内核模块引发了内存泄漏导致大量分页/非分页池占用物理内存

但是如果上述情况发生，最好的办法还是重启后更新相应驱动，因为你无法判断出哪些池内存是可以安全free的。（别听什么营销号“win命令比重启还厉害”，都是扯蛋）

建议：清理一下电脑里的流氓软件（有些国产软件在电脑里乱搞，例如软件没有必要用加载动但还是加载，加载后还出bug，这种是卡顿元凶，直接卸载软件即可）。
如果确定是内存问题，可以使用rammap看一下什么东西占用的内存，更新一下相应驱动，或者某些使用驱动模块的软件（比如杀毒等）。
最后，如果是游戏本身的驱动（TP驱动）导致的卡顿，除非TP自己修复，不然没有办法解决。

**Comment by jkqxl** [comment]
> 系统里运行的东西除了你在任务管理器看见的那些进程，还有内核中运行的东西，就算你只保留某些程序而把其他你看见的进程全部kill掉，依然无法做到流畅，而且手动卸载驱动模块是非常危险且毫无必要的操作。
> 
> 正常情况下如果你关闭一个程序，系统会自动回收他的内存，所以应该没有关了软件还清理不掉内存或清理后仍然卡顿的问题，除非以下极端情况：
> 
> > 进程退出时未卸载或延迟卸载驱动模块，而驱动中仍有内核线程在运行，导致cpu、磁盘占用（点名表扬tp驱动）
> > 某个内核模块引发了内存泄漏导致大量分页/非分页池占用物理内存
> 
> 但是如果上述情况发生，最好的办法还是重启后更新相应驱动，因为你无法判断出哪些池内存是可以安全free的。（别听什么营销号“win命令比重启还厉害”，都是扯蛋）
> 
> 建议：清理一下电脑里的流氓软件（有些国产软件在电脑里乱搞，例如软件没有必要用加载动但还是加载，加载后还出bug，这种是卡顿元凶，直接卸载软件即可）。 如果确定是内存问题，可以使用rammap看一下什么东西占用的内存，更新一下相应驱动，或者某些使用驱动模块的软件（比如杀毒等）。 最后，如果是游戏本身的驱动（TP驱动）导致的卡顿，除非TP自己修复，不然没有办法解决。

暂时会继续尝试使用 xx 命令，观察是否可以有效解决卡顿，如果可以，再回来讨论。
